### ISSUE TITLE
readme 里的这个图跟实际上项目实例预览不一样

### ISSUE THREAD

**Issue by xingyuefeng** [antdpro/antdp#247]
![image](https://github.com/antdpro/antdp/assets/24369183/486c6872-e37d-414e-a81f-28432a54f624)

**Comment by jaywcjlove** [comment]
提供多个示例和多个布局预览 @ChenlingasMx

**Comment by xingyuefeng** [comment]
<img width="990" alt="image" src="https://github.com/antdpro/antdp/assets/24369183/2da0a3ad-2ead-4e0b-b597-69bddf0b6f0b">
@ChenlingasMx 这两个图一样的，没有 tab 选项卡预览图
