### ISSUE TITLE
@antdp/authorized新增localStorage配置

### ISSUE THREAD

**Issue by justcodej** [antdpro/antdp#281]
1. @antdp/authorized默认是获取sessionStorage的authMenu来匹配权限，我现在遇到的问题是后台开发中如果我重新打开一个标签打开页面的话就会停留在登录页，但我的业务需求是需要从新的标签打开，望兼容localStorage。
![WX20240328-191340@2x](https://github.com/antdpro/antdp/assets/33215261/b15fd9a0-e66b-4c56-b8a2-fae2c297161f)

2. 第二个问题从"@antdp/basic-layouts": "2.0.16之后"组件的index.css没有经过编译，样式在safari中不生效
![1711624950515](https://github.com/antdpro/antdp/assets/33215261/6473f6b7-c0f6-49b0-92ba-f59a4c5e952a)

**Comment by jaywcjlove** [comment]
@justcodej 更新 `v2.0.24` 解决来 css 的问题

`1` 的问题我看看能不能添加个配置

**Comment by jaywcjlove** [comment]
@jaywcjlove 配置已经添加 

https://github.com/antdpro/antdp/blob/8aecf6682ad3e645bbefbba5286f7ccb0ad3f3f3/examples/website/docs/guide/config.md?plain=1#L90-L104

**Comment by jaywcjlove** [comment]
@justcodej Upgrade `v2.1.0`

**Comment by justcodej** [comment]
> @justcodej Upgrade `v2.1.0`

1. 升级到最新v2.1.0之后设置了ANTD_IS_STORAGE: false，登录之后也确实是存在了localStorage里，但是location.replace('/welcome')失效了，控制台没有报错，页面登录之后不跳转，我现在的做法是同时保存在localStorage和sessionStorage，可以正常跳转。
2. 点击链接从新窗口打开页面后依旧是需要重新登录，新窗口localStorage里是有authMenu、token之类的数据。

两个问题的点好像都是来自@antdp/authorized在登录鉴权的时候还是通过sessionStorage取值导致，希望是根据@antdp/config来决定是从sessionStorage还是localStorage取值，望排查。

![WX20240329-102657](https://github.com/antdpro/antdp/assets/33215261/6e3270d1-4f05-4fe6-8d7a-dd7b06753bea)

**Comment by justcodej** [comment]
已解决，很高效
